### ISSUE TITLE
Ship generic is missing from generated template

### ISSUE THREAD

**Issue by chennin** [Osiris1975/namelist-mod-gen#12]
`sn_generic` and `sn_frigate` are missing from the generated template and from `namelist.txt`

Run:

```
$ src/namelist_mod_gen/namelist_mod_gen.py -d test.csv
Blank CSV template written to test.csv
$ grep sn_generic test.csv
$
```

It IS present in `template.csv` and the example input CSVs

I was expecting to input a generic ship name list and could not find it in the generated CSV template

**Comment by Osiris1975** [comment]
@chennin thanks, I will update the template file.

**Comment by Osiris1975** [comment]
This is now fixed, output of template command available here:

https://github.com/Osiris1975/namelist-mod-gen/blob/main/examples/template/template.csv
