### ISSUE TITLE
Unable to create namelist

### ISSUE THREAD

**Issue by RowanSkie** [Osiris1975/namelist-mod-gen#3]
**Describe the bug**
With my customized namelist from a modified dumped CSV, trying to make one from said CSV errors out

**To Reproduce**
1. Make a namelist using this: [raxorian.csv](https://github.com/Osiris1975/namelist-mod-gen/files/10813374/raxorian.csv)
2. Error occurs.

**Expected behavior**
Not sure, it doesn't seem to work.

**Screenshots**

**Additional context**
```
Traceback (most recent call last):
  File "D:\Downloads\Applications\namelist_mod_gen\namelist_mod_gen.py", line 148, in <module>
    sys.exit(main())
  File "D:\Downloads\Applications\namelist_mod_gen\namelist_mod_gen.py", line 134, in main
    create_mod(args)
  File "D:\Downloads\Applications\namelist_mod_gen\namelist_mod_gen.py", line 40, in create_mod
    mod_dirs = make_mod_directories(args.mod_name, 'english')
  File "D:\Downloads\Applications\namelist_mod_gen\namelist_mod_gen.py", line 22, in make_mod_directories
    "namelist": os.path.join(c.MOD_OUTPUT_DIR, mod_name, 'common', 'name_lists'),
  File "C:\PL\Python310\lib\ntpath.py", line 143, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\PL\Python310\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

**Comment by RowanSkie** [comment]
Here's my pre-3.6 namelist I was trying to convert to fix the %SEQ% bug, btw, if you need to.
[RAX1.txt](https://github.com/Osiris1975/namelist-mod-gen/files/10813403/RAX1.txt)

**Comment by Osiris1975** [comment]
@RowanSkie thanks, taking a look and will get back to you.

**Comment by RowanSkie** [comment]
Oh, maybe that explains my problem, I'm a Windows 11 guy using Python 3.11.

**Comment by RowanSkie** [comment]
> afaik, %ORD% isn't supported anymore

Oh, I was just following the wiki. It was originally simply %O%.

> the psionic army's sequential token was missing a symbol

That is my fault, might be how I copied things through.

> there were some fields that had sequence tokens that afaik don't support that, like transport names. Did that work for you previously? If it did, I'll look into making the tool support that scenario.

The thing hasn't exactly changed since I made it in Stellaris 2.8, maybe it has changed while I took a break and played other games. Also yeah it used to work.

also, I had just checked which version of Python I had active, and apparently, it was Python 3.10 instead of 3.11...

**Comment by Osiris1975** [comment]
This is working now, I've attached what I generated using the tool as the zip file. I did have to edit your CSV file. A lot has changed since 2.8 and Paradox hasn't been good about informing modders or keeping the docs up to date.

Here's the zipped mod. Feel free to change names and such:
[RAX1-20230223T152105Z-001.zip](https://github.com/Osiris1975/namelist-mod-gen/files/10815342/RAX1-20230223T152105Z-001.zip)

Here's the edited CSV file:

**Comment by RowanSkie** [comment]
Okay, I'm testing it now. One thing I miss with this CSV approach though is that you may have forgotten to add "generic" for ship class names, it still works.

**Comment by Osiris1975** [comment]
@RowanSkie it's all good, its your namelist modify as you like. I do believe the generic fields are in the template, though. I use them in some of my mod's namelists.

What I don't love about the namelist system is that the ship names do double duty: they are both the ship class names and the names of actual ships that've been produced. I wish you could distinguish. between the two.

Let me know when you are done testing, and I'll call this ticket resolved.

**Comment by RowanSkie** [comment]
Yeah, it's all good, forgot to say, haha. Enjoying the %SEQ%-less text on my armies now.
